### ISSUE TITLE
Include/exclude queryparams do not work.

### ISSUE THREAD

**Issue by aaleman** [opencb/cellbase#106]
I am using include/exclude queryparams to include/exclude fields and they do not work.
The WS always returns all fields

Example URL: 
http://wwwdev.ebi.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/clinical/all?include=clinvar&phenotype=Absent%20or%20delayed%20speech%20development&exclude=annot

http://wwwdev.ebi.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/gene/BRCA2/info?include=id

**Comment by imedina** [comment]
As stated in documentation CellBase official host is University of Cambridge since some weeks ago at:
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest

please update the URLs to this as soon as possible. Also, notice that there is a development installation for users keen to test new web services at:
http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest

Regarding the issue this is working fine now at official and development domains:
http://bioinfodev.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/feature/clinical/all?source=clinvar&phenotype=Absent%20or%20delayed%20speech%20development&exclude=annot

Notice the change "source=clinvar", old 'include' tag was avoiding to exclude fields. Thanks for reporting. I mark this as closed since it seems that it is fixed.
