### ISSUE TITLE
README build  directory structure out of date

### ISSUE THREAD

**Issue by justinpaschalldna** [opencb/cellbase#172]
The directory structure listed i the README:
After this you should have this file structure in cellbase-app/build:
cellbase-app/build/
├── bin
├── example
├── libs
├── mongodb-scripts

is out of date, it is now:
cellbase/cellbase-app/target/appassembler/bin
or possibly:
/cellbase/cellbase-app/app

rme-C02PQ280G8WL:app paschall$ ls
bin		example		mongodb-scripts

There is no "build" subdir

AHHHHH - I see that instructions just are missing to say to run ./build.sh that creates the "build" subdir --- unless I miss where it says to do that after running mvn clean install -DskipTests

**Comment by imedina** [comment]
Thank you very much @justinpaschalldna!  Your issue is timely, I just removed the build.sh from CellBase, this was the old way, now old OpenCB projects implement the building in the pom.xml, you can see #174 

You can give a quick try by executing "mvn install -DskipTests" in the 'develop' branch, a 'build' folder will be created in the root folder of CellBase. README has also been updated.
