### ISSUE TITLE
hpo parsing error

### ISSUE THREAD

**Issue by mbsimonovic** [opencb/cellbase#260]
branch develop, [BuildCommandExecutor](https://github.com/opencb/cellbase/blob/838fb47f85278da41518454bf384847d669f21db/cellbase-app/src/main/java/org/opencb/cellbase/app/cli/BuildCommandExecutor.java) will try to [parse](https://github.com/opencb/cellbase/blob/838fb47f85278da41518454bf384847d669f21db/cellbase-app/src/main/java/org/opencb/cellbase/app/cli/BuildCommandExecutor.java#L410) hpo (ALL_SOURCES_ALL_FREQUENCIES_diseases_to_genes_to_phenotypes.txt) using DisgenetParser but that won't work since they have quite different formats.

**Comment by javild** [comment]
That's correct. Thank you very much for your comment.

Actually neither HPO nor Disgenet need to have their own build code since both of them are integrated within the Gene model - In other words, both HPO and Disgenet are built when the Gene model is built (--data gene) and integrated within the gene.json file. 

Both methods at BuildCommandExecutor and the DisgenetParser class have been marked as Deprecated, the corresponding entries in the switch block removed
