### ISSUE TITLE
Inconsistent annotation for different encodings [TC:T] vs [C:-] of the same variant

### ISSUE THREAD

**Issue by mh11** [opencb/cellbase#305]
I tried to annotate one variant. Depending on the naming convention, I get different results:

- 2:203332264:TC:T [link](http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/variant/2:203332264:TC:T/annotation)
  - returns __synonymous_variant__

- 2:203332265:C:- [link](http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v3/hsapiens/genomic/variant/2:203332265:C:-/annotation)
  - returns __frameshift_variant__

Since it is the same variant encoded in different ways, it should always return the same result.

**Comment by javild** [comment]
Hi Matthias,

Thanks for your comment.

Two points: first, please move to the v4 version, many new features were included since versions 3.* (including normalization). Second, normalization is deactivated by default. Therefore, the annotator is expecting the variants to be appropriately formatted according to the OpenCB models. You can enable normalization by using the query parameter "normalize=true". Thus, you will find that these URLs return the same result:

http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/genomic/variant/2:203332264:TC:T/annotation?normalize=true
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/genomic/variant/2:203332265:C:-/annotation?normalize=true
http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/genomic/variant/2:203332265:C:-/annotation

We shall appropriately document how variant strings are treated by the RESTful API indeed. 

Apologies for the inconvenience.
