### ISSUE TITLE
Slow queries for genes by expressions

### ISSUE THREAD

**Issue by j-coll** [opencb/cellbase#330]
In OpenCGA we relay on Cellbase for executing expression queries. I am seeing slow timing with this type of queries. It seems that this field is not indexed. Should it be indexed?

We are also planning to use the "annotation.expression.value" for referring to UP and DOWN expressions (see #245). Maybe it would be interesting to have a composed index between tissue and value.

http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/feature/gene/search?include=name,chromosome,start,end&annotation.expression.tissue=skin&limit=1

**Comment by javild** [comment]
It was not a problem related with the mongo index. Creating the mongo index made the query even slower. The problem was related with the second count query issued to fill in the numTotalResults field of the QueryResult object.

The skipCount option has been enabled in the Web Services layer and the query runs extremely fast now:
http://bioinfodev.hpc.cam.ac.uk/cellbase-4.5.0-SNAPSHOT/webservices/rest/v4/hsapiens/feature/gene/search?include=name,chromosome,start,end,annotation.expression&annotation.expression.tissue=skin&annotation.expression.value=UP&limit=1&skipCount=true
